services:
  - type: web
    name: staysmart-ai-service
    runtime: python
    repo: https://github.com/kainatmasood/staysmart-ai
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
